### ISSUE TITLE
Plugin ChunkLoader v2.2 generated an exception while executing task

### ISSUE THREAD

**Issue by BoJockel** [KayTeam-Studio/ChunkLoader#1]
Good evening!

Server Info:
OS: Ubuntu 21.04 Server
MC Server: Paper 1.17
Java Version: OpenJDK 16

I get a error in the console every time i add a chunk.

The error:

[20:26:13 WARN]: [ChunkLoader] Plugin ChunkLoader v2.2 generated an exception while executing task 6406
java.lang.IllegalStateException: Asynchronous chunk load!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.jar:git-Paper-"22280c5"]
        at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.loadChunk(CraftWorld.java:597) ~[patched_1.17.jar:git-Paper-"22280c5"]
        at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.loadChunk(CraftWorld.java:501) ~[patched_1.17.jar:git-Paper-"22280c5"]
        at org.kayteam.chunkloader.main.ChunkLoader$1$1.run(ChunkLoader.java:100) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-"22280c5"]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.jar:git-Paper-"22280c5"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.jar:git-Paper-"22280c5"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]

Hope you will find a solution!

**Comment by BoJockel** [comment]
edit: the error gets also thrown on server start.

**Comment by segu23** [comment]
Solved in v2.5
